<p>
The Appwrite CLI can be used in a non-interactive and headless manner, without saving configuration or sessions. This is especially useful when you want to automate tasks on a CI server.
</p>
<h2><a href="/docs/commandline-ci#CIMode" id="CIMode">CI Mode</a></h2>

<p>You can enable CI mode for the Appwrite CLI by setting the <b>project ID, endpoint, and API Key</b>:</p>

<div class="ide margin-bottom" data-lang="bash" data-lang-label="CLI">
    <pre class="line-numbers"><code class="prism language-bash" data-prism>appwrite client \
--endpoint https://[HOSTNAME_OR_IP]/v1 \
--projectId [YOUR_PROJECT_ID] \
--key YOUR_API_KEY</code></pre>
</div>

<p>When you set the global configuration parameters using the <code>appwrite client</code> command, they take precedence over the local configuration parameters in your <code>appwrite.json</code> thereby switching the CLI to non-interactive mode. </p> 

<p>In this mode, the CLI can only interact with one project at a time.</p>

<h2><a href="/docs/commandline-ci#keys" id="keys">API Keys</a></h2>
<p>In CI mode, the CLI uses an <b>API key</b> to authenticate. Your API key must have sufficient permissions to execute the commands you plan to use. <a href="/docs/keys">Learn more about API Keys</a>.</p>

<h2><a href="/docs/command-line-ci#configuration" id="configuration">Configuration</a></h2>

<p>At any point, if you would like to change your server's endpoint, project ID, or self-signed certificate acceptance, use the <code>client</code> command.</p>

<div class="ide margin-bottom" data-lang="bash" data-lang-label="CLI">
    <pre class="line-numbers"><code class="prism language-bash" data-prism>appwrite client --endpoint https://[HOSTNAME_OR_IP]/v1
appwrite client --key 23f24gwrhSDgefaY
appwrite client --selfSigned true
appwrite client --reset // Resets your CLI configuration
appwrite client --debug // Prints your current configuration</code></pre>
</div>