<p>Appwrite uses emails messages to perform user invite, user verification, login, and reset password. Emails messages can be customized to fit your app's design and voice.</p>

<h2><a href="#customize" id="customize">Customize Templates</a></h2>
<p>You can customize email templates in the Appwrite console.</p>
<div class="notice">
    <h2>Custom SMTP Server Required</h2>
    <p>The built-in email service does not support custom email templates. Configure a <a href="#smtp">custom SMTP server</a> to enable custom email templates.</p>
</div>
<ol class="margin-top margin-bottom-large text-size-normal">
    <li>In your project, navigate to the <b>Auth</b> service.</li>
    <li>Under the <b>Auth</b> service, navigate to the <b>Templates</b> tab.</li>
    <li>Expand the email template you want to edit.</li>
    <li>Select the <b>Template language</b>. You can have a different template for each language your app supports.</li>
    <li>Update the email template fields and click **Update** to save your changes.</li>
</ol>
<h2><a href="#email-templates" id="email-templates">Email Templates</a></h2>
<p>You can customize the email emplates for account verification, magic-url authentication, password resets, and user invites.</p>
<h3><a href="#email-template-components" id="email-template-components">Email Template Components</a></h3>
<p>Each email templates has the following components that you can customize.</p>
<h2 id="permission-types"><a href="/docs/permissions#permission-types">Permission Types</a></h2>
<p>In Client and Server SDKs, you will find a <b>Permission</b> class with helper methods for each role described below.</p>
<table class="full text-size-small">
    <thead>
    <tr>
        <td style="width: 200px">Component</td>
        <td>Description</td>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>Sender name</td>
        <td>Readers will see this as display name of the sender.</td>
    </tr>
    <tr>
        <td>Sender email</td>
        <td>Readers will see this as the displayed email of the sender. This must be a valid email for the SMTP provider your configured.</td>
    </tr>
    <tr>
        <td>Reply to</td>
        <td>Readers will reply to this email adress instead of the sender address. You can leave this field empty if unused.</td>
    </tr>
    <tr>
        <td>Subject</td>
        <td>The title of the email.</td>
    </tr>
    <tr>
        <td>Message</td>
        <td>The body of the email. You can find the variables available in the <a href="#email-template-syntax">Email Template Syntax</a> section.</td>
    </tr>
    </tbody>
</table>
<h3><a href="#email-template-syntax" id="email-template-syntax">Email Template Syntax</a></h3>
<p>Variables can be used in email templates to dynamically format unique emails for each reader. These variables can only be accessed in the <b>Message</b> field of the email template.</p>

<table class="full text-size-small">
    <thead>
    <tr>
        <td style="width: 200px">Variable</td>
        <td>Description</td>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td><code>{{project}}</code></td>
        <td>The project name.</td>
    </tr>
    <tr>
        <td><code>{{team}}</code></td>
        <td>Thee project team's name.</td>
    </tr>
    <tr>
        <td><code>{{user}}</code></td>
        <td>The name of the user receiving the email.</td>
    </tr>
    <tr>
        <td><code>{{redirect}}</code></td>
        <td>The URL for the user to complete the email template's action.</td>
    </tr>
    </tbody>
</table>

<h2><a href="#sms-templates" id="sms-templates">SMS Templates</a></h2>
<p>You can customize the SMS emplates used for phone verification and login.</p>
<h3><a href="#sms-template-components" id="sms-template-components">SMS Template Components</a></h3>
<table class="full text-size-small">
    <thead>
    <tr>
        <td style="width: 200px">Component</td>
        <td>Description</td>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>Message</td>
        <td>The body of the SMS message. You can find the variables available in the <a href="#sms-template-syntax">SMS Template Syntax</a> section.</td>
    </tr>
    </tbody>
</table>

<h3><a href="#sms-template-syntax" id="sms-template-syntax">SMS Template Syntax</a></h3>
<p>Variables can be used in SMS templates to dynamically format unique messages for each reader.</p>

<table class="full text-size-small">
    <thead>
    <tr>
        <td style="width: 200px">Variable</td>
        <td>Description</td>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td><code>{{project}}</code></td>
        <td>The project name.</td>
    </tr>
    <tr>
        <td><code>{{team}}</code></td>
        <td>Thee project team's name.</td>
    </tr>
    <tr>
        <td><code>{{user}}</code></td>
        <td>The name of the uer receiving the email.</td>
    </tr>
    <tr>
        <td><code>{{passcode}}</code></td>
        <td>The secret code sent to users for phone verification or authentication.</td>
    </tr>
    </tbody>
</table>