<p>
    Appwrite Functions offer a familiar interface if you've developed REST endpoints.
    Each function is handled following a request and response pattern.
    Here's what you need to know to start writing your first Appwrite Function.
</p>

[TODO: CTA if you just want examples, click this link]

<h2><a href="#context" id="context">The Context Object</a></h2>

<h3><a href="#request" id="request">Request</a></h3>

<h3><a href="#response" id="response">Response</a></h3>

<h3><a href="#logging" id="logging">Logging</a></h3>
-> LIST WHAT WE SHOW AND WHAT WE DONT SHOW

<h2><a href="#environment-variables" id="environment-variables">Accessing Environment Variables</a></h2>

<h2><a href="#dependencies" id="dependencies">Depencies</a></h2>

<h2><a href="#appwrite" id="appwrite">Using Appwrite in a Function</a></h2>
[TODO: 2 examples -> JWT and API keys]

<h2><a href="#recipes" id="recipes">Recipes</a></h2>
[TODO: Matej and Luke write examples]

<h2><a href="#limitations" id="limitations">Limitations</a></h2>
<!-- <p>Libraries dependent on</p> -->