<?php

use Appwrite\Utopia\View;

$events = $this->getParam('events', []);
$runtimes = $this->getParam('runtimes', []);

$sorted_runtimes = [];

foreach ($runtimes as $key => $item) {
    $name = $item['name'];
    
    if (!isset($sorted_runtimes[$name])) {
        $sorted_runtimes[$name] = [];
    }

    $item['version'] = $key;

    $sorted_runtimes[$name]['versions'][] = $item;
}

$sorted_runtimes['Node.js']["cloud"] = true;
$sorted_runtimes['PHP']["cloud"] = true;
$sorted_runtimes['Ruby']["cloud"] = true;
$sorted_runtimes['Python']["cloud"] = true;
$sorted_runtimes['Dart']["cloud"] = true;
?>


<p>
    Appwrite Functions supports an extensive list of runtimes to meet your unique tech preferences.
    Not all runtimes are available on Appwrite Cloud yet. Check for the <span class="tag green">Cloud</span> label in each listed runtime to know which ones are available.
</p>

<h2><a href="/docs/functions#supportedRuntimes" id="supportedRuntimes">Supported Runtimes</a></h2>

<p>Below is a list of supported Functions runtimes. The Appwrite team continually adds support for new runtimes.</p>

<table cellspacing="0" cellpadding="0" border="0" class="full margin-bottom-large">
    <thead>
        <tr>
            <th style="width: 50px"></th>
            <th style="width: 80px">Name</th>
            <th>Image</th>
            <th  style="width: 100px">Architectures</th>
            <th  style="width: 140px">Platforms</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($sorted_runtimes as $key => $runtime): ?>
        <tr>
            <td>
                <img src="" data-ls-attrs="src=/images/runtimes/<?php echo $this->escape($runtime['versions'][0]['logo'] ?? ''); ?>" alt="Function Env." class="avatar xxs" />
            </td>
            <td>
                <?php echo $this->escape($key); ?>
            </td>
            <td>
            <?php foreach($runtime['versions'] as $key => $version): ?>
                <a href="https://hub.docker.com/r/<?php echo $this->escape(strtok($version['image'], ':')); ?>" target="_blank" rel="noopener"><?php echo $this->escape($version['image'] ?? ''); ?> <i class="icon-link-ext"></i></a>
            <?php endforeach; ?>
            </td>
            <td><?php echo $this->escape(implode(' / ', $runtime['versions'][0]['supports'] ?? [])); ?></td>
            <td>
                <span class="tag">Self-hosted</span>         
                <?php if (isset($runtime["cloud"])): ?>
                    <span class="tag green">Cloud</span>
                <?php endif; ?>  
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>