<p>
  Appwrite Functions is all about flexibility.
  Behind the simple workflow hides some useful recipes that can help you accomplish your goals faster.
  Take a look at the following.
</p>
[TODO: @matej @luke -> Let's have some simple recipes here for common actions]

<h4>Getting Started</h4>

<p>
  In this recipe, we'll build a simple function for currency conversion.
</p>

<ul class="phases clear" data-ui-phases>
  <li>
    <h3>Node.js</h3>
    <div>
      <p>Create a new file, `index.js`.</p>
      <p>Add the following code to `index.js`.</p>
      <div class="ide margin-top-small" data-lang="javascript" data-lang-label="JavaScript">
        <pre class="line-numbers"><code class="prism language-js" data-prism>export default async function ({ res }) {
  return res.send('1.13');
};</code></pre>
      </div>
    </div>
  </li>
  <li>
    <h3>PHP</h3>
    <div>
      <p>Create a new file, `index.php`.</p>
      <p>Add the following code to `index.php`.</p>
      <div class="ide margin-top-small" data-lang="php" data-lang-label="PHP">
        <pre class="line-numbers"><code class="prism language-php" data-prism>&lt;?php
return function ($context) {
  return $context-&gt;res-&gt;send('1.13');
};</code></pre>
      </div>
    </div>
  </li>
  <li>
    <h3>Python</h3>
    <div>
      <p>Create a new file, `index.py`.</p>
      <p>Add the following code to `index.py`.</p>
      <div class="ide margin-top-small" data-lang="python" data-lang-label="Python">
        <pre class="line-numbers"><code class="prism language-python" data-prism>def main(context):
  return context.res.send('1.13')</code></pre>
      </div>
    </div>
  </li>
  <li>
    <h3>Dart</h3>
    <div>
      <p>Create a new file, `index.dart`.</p>
      <p>Add the following code to `index.dart`.</p>
      <div class="ide margin-top-small" data-lang="dart" data-lang-label="Dart">
        <pre class="line-numbers"><code class="prism language-dart" data-prism>import 'dart:async';

Future&lt;dynamic&gt; main(final context) async {
  return context.res.send('1.13');
}</code></pre>
      </div>
    </div>
  </li>
  <li>
    <h3>Ruby</h3>
    <div>
      <p>Create a new file, `index.rb`.</p>
      <p>Add the following code to `index.rb`.</p>
      <div class="ide margin-top-small" data-lang="ruby" data-lang-label="Ruby">
        <pre class="line-numbers"><code class="prism language-ruby" data-prism>def main(context)
  return context.res.send('1.13')
end</code></pre>
      </div>
    </div>
  </li>
</ul>

<p>This code will return `1.13` when the function is called, because 1€ equals approximately 1.13$.</p>
<p>Now, create a function in the Appwrite console, adding your Git repository as the remote source and using the path file you created as the entry point.</p>
<li>Finally, execute the function and visit the URL (like `ghrfu9ewji.functions.appwrite.app`) to see the response.</li>

<h4>Currency Conversion</h4>

<p>Now, let's update the function to use the request payload.</p>
<p>You can use a query string to pass data to your function. For example, `ghrfu9ewji.functions.appwrite.app?amount=5` will pass `5` as the `amount` parameter.</p>

<ul class="phases clear" data-ui-phases>
  <li>
    <h3>Node.js</h3>
    <div>
      <p>Update `index.js` to use `req.query.amount` to access the `amount` parameter, and return the conversion result.</p>
      <div class="ide margin-top-small" data-lang="javascript" data-lang-label="JavaScript">
        <pre class="line-numbers"><code class="prism language-js" data-prism>export default async function ({ req, res }) {
  const amountInEuros = Number(req.query.amount);
  const amountInDollars = amountInEuros * 1.13;
  return res.send(amountInDollars.toString());
};</code></pre>
      </div>
    </div>
  </li>
  <li>
    <h3>PHP</h3>
    <div>
      <p>Update `index.php` to use `$context->req->query['amount']` to access the `amount` parameter, and return the conversion result.</p>
      <div class="ide margin-top-small" data-lang="php" data-lang-label="PHP">
        <pre class="line-numbers"><code class="prism language-php" data-prism>&lt;?php
return function ($context) {
  $amountInEuros = $context-&gt;req-&gt;query['amount'];
  $amountInDollars = $amountInEuros * 1.13;
  return $context-&gt;res-&gt;send($amountInDollars);
};</code></pre>
      </div>
    </div>
  </li>
  <li>
    <h3>Python</h3>
    <div>
      <p>Update `index.py` to use `context.req.query['amount']` to access the `amount` parameter, and return the conversion result.</p>
      <div class="ide margin-top-small" data-lang="python" data-lang-label="Python">
        <pre class="line-numbers"><code class="prism language-python" data-prism>def main(context):
  amountInEuros = context.req.query['amount']
  amountInDollars = amountInEuros * 1.13
  return context.res.send(amountInDollars)</code></pre>
      </div>
    </div>
  </li>
  <li>
    <h3>Dart</h3>
    <div>
      <p>Update `index.dart` to use `context.req.query['amount']` to access the `amount` parameter, and return the conversion result.</p>
      <div class="ide margin-top-small" data-lang="dart" data-lang-label="Dart">
        <pre class="line-numbers"><code class="prism language-dart" data-prism>import 'dart:async';

Future&lt;dynamic&gt; main(final context) async {
  final amountInEuros = context.req.query['amount'];
  final amountInDollars = amountInEuros * 1.13;
  return context.res.send(amountInDollars);
}</code></pre>
      </div>
    </div>
  </li>
  <li>
    <h3>Ruby</h3>
    <div>
      <p>Update `index.rb` to use `context.req.query['amount']` to access the `amount` parameter, and return the conversion result.</p>
      <div class="ide margin-top-small" data-lang="ruby" data-lang-label="Ruby">
        <pre class="line-numbers"><code class="prism language-ruby" data-prism>def main(context)
  amountInEuros = context.req.query['amount']
  amountInDollars = amountInEuros * 1.13
  return context.res.send(amountInDollars)
end</code></pre>
      </div>
    </div>
  </li>
</ul>

<p>Commit your changes and push them to your Git repository.</p>


<h4>Testing the function</h4>

<p>
  Execute the function and visit the URL (like `ghrfu9ewji.functions.appwrite.app?amount=5`) to see the response.
</p>
<p>
  You should see the result of the conversion, like `5.65`.
</p>

<h4>Adding Dependencies</h4>

<ul class="phases clear" data-ui-phases>
  <li>
    <h3>Node.js</h3>
    <div>
      <p>Run the following bash command to create a `package.json` file. This file is used to manage your Node.js project's dependencies.</p>
      <div class="ide margin-top-small" data-lang="bash" data-lang-label="Bash">
        <pre class="line-numbers"><code class="prism language-bash" data-prism>npm init -y</code></pre>
      </div>
      <p>Install the `undici` library. This library includes a `fetch` function that you can use to make HTTP requests.</p>
      <div class="ide margin-top-small" data-lang="bash" data-lang-label="Bash">
        <pre class="line-numbers"><code class="prism language-bash" data-prism>npm install undici</code></pre>
      </div>
      <p>Finally, add `npm install` to your function's build commands in the Appwrite console.</p>
    </div>
  </li>
  <li>
    <h3>PHP</h3>
    <div>
      <p>You can use Composer to manage your PHP project's dependencies. Install it from <a href="https://getcomposer.org/download/" target="_blank">getcomposer.org/download</a>.</p>
      <p>Run the following bash command to create a `composer.json` file. This file is used to manage your PHP project's dependencies.</p>
      <div class="ide margin-top-small" data-lang="bash" data-lang-label="Bash">
        <pre class="line-numbers"><code class="prism language-bash" data-prism>composer init -y</code></pre>
      </div>
      <p>Install the `guzzlehttp/guzzle` library. This library includes a `get` function that you can use to make HTTP requests.</p>
      <div class="ide margin-top-small" data-lang="bash" data-lang-label="Bash">
        <pre class="line-numbers"><code class="prism language-bash" data-prism>composer require guzzlehttp/guzzle</code></pre>
      </div>
      <p>Finally, add `composer install` to your function's build commands in the Appwrite console.</p>
    </div>
  </li>
  <li>
    <h3>Python</h3>
    <div>
      <p>Run the following bash command to create a `requirements.txt` file. This file is used to manage your Python project's dependencies.</p>
      <div class="ide margin-top-small" data-lang="bash" data-lang-label="Bash">
        <pre class="line-numbers"><code class="prism language-bash" data-prism>touch requirements.txt</code></pre>
      </div>
      <p>Install the `requests` library. This library includes a `get` function that you can use to make HTTP requests.</p>
      <div class="ide margin-top-small" data-lang="bash" data-lang-label="Bash">
        <pre class="line-numbers"><code class="prism language-bash" data-prism>echo "requests" &gt;&gt; requirements.txt
pip -r requirements.txt</code></pre>
      </div>
      <p>Finally, add `pip install -r requirements.txt` to your function's build commands in the Appwrite console.</p>
    </div>
  </li>
  <li>
    <h3>
      Dart
    </h3>
    <div>
      <p>
        Create a `pubspec.yaml` file with the following contents. This file is used to manage your Dart project's dependencies.
      </p>
      <div class="ide margin-top-small" data-lang="yaml" data-lang-label="YAML">
        <pre class="line-numbers"><code class="prism language-yaml" data-prism>name: appwrite_function
description: Appwrite Function
version: 1.0.0
environment:
  sdk: '&gt;=2.12.0 &lt;3.0.0'
</code></pre>
      </div>
      <p>
        Install the `http` library. This library includes a `get` function that you can use to make HTTP requests.
      </p>
      <div class="ide margin-top-small" data-lang="bash" data-lang-label="Bash">
        <pre class="line-numbers"><code class="prism language-bash" data-prism>
          pub install http
      </div>
      <p>
        Finally, add `pub get` to your function's build commands in the Appwrite console.
      </p>
    </div>
  </li>
  <li>
    <h3>
      Ruby
    </h3>
    <div>
      <p>
        Create a `Gemfile` file with the following contents. This file is used to manage your Ruby project's dependencies.
      </p>
      <div class="ide margin-top-small" data-lang="ruby" data-lang-label="Ruby">
        <pre class="line-numbers"><code class="prism language-ruby" data-prism>source 'https://rubygems.org'
        </code></pre>
      </div>
      <p>
        Install the `httparty` library. This library includes a `get` function that you can use to make HTTP requests.
      </p>
      <div class="ide margin-top-small" data-lang="bash" data-lang-label="Bash">
        <pre class="line-numbers"><code class="prism language-bash" data-prism>echo "gem 'httparty'" &gt;&gt; Gemfile
bundle install</code></pre>
      </div>
      <p>
        Finally, add `bundle install` to your function's build commands in the Appwrite console.
      </p>
    </div>
  </li>
</ul>

<h4>Using Dependencies</h4>

<ul class="phases clear" data-ui-phases>
  <li>
    <h3>Node.js</h3>
    <div>
      <p>Use `fetch` from `undici` to get the current conversion rate. This API call will return the current conversion rate between Euros and Dollars.</p>
      <div class="ide margin-top-small" data-lang="javascript" data-lang-label="JavaScript">
        <pre class="line-numbers"><code class="prism language-js" data-prism>import { fetch } from 'undici';

export default async function ({ req, res }) {
  const amountInEuros = Number(req.query.amount);
  const response = await fetch('https://api.exchangerate.host/latest?base=EUR&symbols=USD');
  const data = await response.json();
  const amountInDollars = amountInEuros * data.rates.USD;
  return res.send(amountInDollars.toString());
};</code></pre>
      </div>
    </div>
  </li>
  <li>
    <h3>PHP</h3>
    <div>
      <p>
      <div class="ide margin-top-small" data-lang="php" data-lang-label="PHP">
        <pre class="line-numbers"><code class="prism language-php" data-prism>&lt;?php

require(__DIR__ . '/../vendor/autoload.php');

use GuzzleHttp\Client;

return function (&#36;context) {
  &#36;amountInEuros = &#36;context-&gt;getRequest()-&gt;getQuery('amount');
  &#36;client = new Client();
  &#36;response = &#36;client-&gt;get('https://api.exchangerate.host/latest?base=EUR&amp;symbols=USD');
  &#36;data = json_decode(&#36;response-&gt;getBody(), true);
  &#36;amountInDollars = &#36;amountInEuros * &#36;data['rates']['USD'];
  return &#36;context-&gt;res-&gt;send(strval(&#36;amountInDollars));
};</code></pre>
      </div>
    </div>
  </li>
  <li>
    <h3>Python</h3>
    <div>
      <p>Use `get` from `requests` to get the current conversion rate. This API call will return the current conversion rate between Euros and Dollars.</p>
      <div class="ide margin-top-small" data-lang="python" data-lang-label="Python">
        <pre class="line-numbers"><code class="prism language-python" data-prism>import requests

def main(context):
  amount_in_euros = float(context.req.query['amount'])
  response = requests.get('https://api.exchangerate.host/latest?base=EUR&symbols=USD')
  data = response.json()
  amount_in_dollars = amount_in_euros * data['rates']['USD']
  return context.res.send(str(amount_in_dollars))</code></pre>
      </div>
    </div>
  </li>
  <li>
    <h3>Dart</h3>
    <div>
      <p>Use `get` from `http` to get the current conversion rate. This API call will return the current conversion rate between Euros and Dollars.</p>
      <div class="ide margin-top-small" data-lang="dart" data-lang-label="Dart">
        <pre class="line-numbers"><code class="prism language-dart" data-prism>import 'dart:async';
import 'package:http/http.dart' as http;

Future&lt;dynamic&gt; main(final context) async {
  final amountInEuros = double.parse(context.req.query['amount'])
  final response = await http.get(Uri.parse('https://api.exchangerate.host/latest?base=EUR&symbols=USD'));
  final data = json.decode(response.body);
  final amountInDollars = amountInEuros * data['rates']['USD'];
  return context.res.send(amountInDollars.toString());
}</code></pre>
      </div>
    </div>
  </li>
  <li>
    <h3>Ruby</h3>
    <div>
      <p>Use `get` from `httparty` to get the current conversion rate. This API call will return the current conversion rate between Euros and Dollars.</p>
      <div class="ide margin-top-small" data-lang="ruby" data-lang-label="Ruby">
        <pre class="line-numbers"><code class="prism language-ruby" data-prism>require 'httparty'

def main(context)
  amount_in_euros = context.req.query['amount'].to_f
  response = HTTParty.get('https://api.exchangerate.host/latest?base=EUR&symbols=USD')
  data = JSON.parse(response.body)
  amount_in_dollars = amount_in_euros * data['rates']['USD']
  return context.res.send(amount_in_dollars.to_s)
end</code></pre>
      </div>
    </div>
  </li>
</ul>

<p>Deploy your changes</p>
<p>After your function has updated, you can test it by visiting the URL and providing different amounts to convert in the query string. The conversion rate should now be more precise because we're using the current conversion rate.</p>

<h4>Adding More Routes</h4>

<p>Let's add support multiple paths like `/eur` and `/inr`. Each path will convert from that currency to dollars.</p>

<ul class="phases clear" data-ui-phases>
  <li>
    <h3>Node.js</h3>
    <div>
      <p>
      <div class="ide margin-top-small" data-lang="javascript" data-lang-label="JavaScript">
        <pre class="line-numbers"><code class="prism language-js" data-prism>import { fetch } from 'undici';

export default async function ({ req, res }) {
  if (req.path === '/eur') {
    const amountInEuros = Number(req.query.amount);
    const response = await fetch('https://api.exchangerate.host/latest?base=EUR&symbols=USD');
    const data = await response.json();
    const amountInDollars = amountInEuros * data.rates.USD;
    return res.send(amountInDollars.toString());
  }

  if (req.path === '/inr') {
    const amountInRupees = Number(req.query.amount);
    const response = await fetch('https://api.exchangerate.host/latest?base=INR&symbols=USD');
    const data = await response.json();
    const amountInDollars = amountInRupees * data.rates.USD;
    return res.send(amountInDollars.toString());
  }

  return res.send('Invalid path');
};</code></pre>
      </div>
    </div>
  </li>
  <li>
    <h3>Python</h3>
    <div>
      <p>
      <div class="ide margin-top-small" data-lang="python" data-lang-label="Python">
        <pre class="line-numbers"><code class="prism language-python" data-prism>import requests

def main(context):
  if context.req.path == '/eur':
    amount_in_euros = float(context.req.query['amount'])
    response = requests.get('https://api.exchangerate.host/latest?base=EUR&symbols=USD')
    data = response.json()
    amount_in_dollars = amount_in_euros * data['rates']['USD']
    return context.res.send(str(amount_in_dollars))

  if context.req.path == '/inr':
    amount_in_rupees = float(context.req.query['amount'])
    response = requests.get('https://api.exchangerate.host/latest?base=INR&symbols=USD')
    data = response.json()
    amount_in_dollars = amount_in_rupees * data['rates']['USD']
    return context.res.send(str(amount_in_dollars))

  return 'Invalid path'</code></pre>
      </div>
    </div>
  </li>
  <li>
    <h3>Dart</h3>
    <div>
      <p>
      <div class="ide margin-top-small" data-lang="dart" data-lang-label="Dart">
        <pre class="line-numbers"><code class="prism language-dart" data-prism>import 'dart:async';
import 'package:http/http.dart' as http;

Future&lt;dynamic&gt; main(final context) async {
  if (context.req.path == '/eur') {
    final amountInEuros = double.parse(context.req.query['amount'])
    final response = await http.get(Uri.parse('https://api.exchangerate.host/latest?base=EUR&symbols=USD'));
    final data = json.decode(response.body);
    final amountInDollars = amountInEuros * data['rates']['USD'];
    return context.res.send(amountInDollars.toString());
  }

  if (context.req.path == '/inr') {
    final amountInRupees = double.parse(context.req.query['amount'])
    final response = await http.get(Uri.parse('https://api.exchangerate.host/latest?base=INR&symbols=USD'));
    final data = json.decode(response.body);
    final amountInDollars = amountInRupees * data['rates']['USD'];
    return context.res.send(amountInDollars.toString());
  }

  return 'Invalid path';
}</code></pre>
      </div>
    </div>
  </li>
  <li>
    <h3>Ruby</h3>
    <div>
      <p>
      <div class="ide margin-top-small" data-lang="ruby" data-lang-label="Ruby">
        <pre class="line-numbers"><code class="prism language-ruby" data-prism>require 'httparty'

def main(context)
  if context.request.path == '/eur'
    amount_in_euros = context.request.query['amount'].to_f
    response = HTTParty.get('https://api.exchangerate.host/latest?base=EUR&symbols=USD')
    data = JSON.parse(response.body)
    amount_in_dollars = amount_in_euros * data['rates']['USD']
    return context.response.send(amount_in_dollars.to_s)
  end

  if context.request.path == '/inr'
    amount_in_rupees = context.request.query['amount'].to_f
    response = HTTParty.get('https://api.exchangerate.host/latest?base=INR&symbols=USD')
    data = JSON.parse(response.body)
    amount_in_dollars = amount_in_rupees * data['rates']['USD']
    return context.response.send(amount_in_dollars.to_s)
  end

  return 'Invalid path'
end</code></pre>
      </div>
    </div>
  </li>

</ul>

<p>After your function has updated, you can try out the new paths. For example, `ghrfu9ewji.functions.appwrite.app/eur?amount=5` should convert Euros to Dollars, while `ghrfu9ewji.functions.appwrite.app/inr?amount=100` should convert Indian Rupees to Dollars.</p>
<p>Congratulations! You've built a powerful currency conversion function using Appwrite!</p>

[TODO: @luke -> translate code for other runtimes]

[TODO: @matej @luke -> Example with JWT, show both client and server code]

<!-- Here's more ideas -->

<!-- 
  How to handle different methods (POST, GET, PUT,DELETE)
  How to handle different paths (/users, /articles, ...)
  How to cache response (cache headers, json)
  How to file response (send img file, also cache it)
  How to handle HTML form submittion
  How to do basic auth (there is some header for it)
  How to recieve data in body
  How to recieve data in URL params
  How to redirect
  How to log
  How to do Bearer Auth
  How to access event data
  How to access env vars 
-->