<p>
    Appwrite Functions are mini application in Appwrite with their own endpoint. 
    Each function can have many deployments, which can be thought of as versions of the mini-application.
</p>

<p>
    Functions can be deployed in different ways to meet your unique development habbits.
    You can automatically deploy Appwrite Functions from source control, build your own deployment pipelines using the Appwrite CLI, or upload code files manually.
    Here's everything you need to know to deploy your first Appwrite Function.
</p>

<h2><a href="#vcs" id="vcs">Version Control Systems</a></h2>
<p>
    The recommended way to manage your Appwrite Function deployments is to use a version control system, such as GitHub.
    This offers simple versioning and collaboration that will easily fit into the rest of your development workflow.
</p>

[TODO: Describe how to create a GitHub deployment]

<h3>Create</h3>
<h3>Deploy</h3>
<h3>...</h3>
<h3>Profit?!</h3>

<h3><a href="#templates" id="templates">Templates</a></h3>

<h2><a href="#cli" id="cli">CLI</a></h2>
[TODO]

<h2><a href="#manual" id="manual">Manual</a></h2>
[TODO]

<h2><a href="#life-cycle" id="life-cycle">Deployment Life Cycle</a></h2>
<p>Deployments will go through the following states throughout their life cycle.</p>
[TODO: @matej, describe the life cycle of a deployment (like being uploaded, built, etc)]

[TODO: @matej What else?]