<?php

use Appwrite\Utopia\View;

$events = $this->getParam('events', []);
$runtimes = $this->getParam('runtimes', []);
$runtimes['node-16.0']["cloud"] = true;
$runtimes['node-18.0']["cloud"] = true;
$runtimes['php-8.0']["cloud"] = true;
$runtimes['ruby-3.0']["cloud"] = true;
$runtimes['python-3.9']["cloud"] = true;
$runtimes['dart-2.17']["cloud"] = true;
?>


<p>
    Appwrite Functions supports an extensive list of runtimes to meet your unique tech preferences.
    Not all runtimes are available on Appwrite Cloud, check for the <code>Cloud</code> label in each listed runtime to know whichones are available.
</p>

<h2><a href="/docs/functions#supportedRuntimes" id="supportedRuntimes">Supported Runtimes</a></h2>

<p>Appwrite provides multiple code runtimes to execute your custom functions. Each runtime uses a Docker image tied to a specific language version to provide a safe, isolated playground to run your team's code.</p>

<p>Below is a list of supported Cloud Functions runtimes. The Appwrite team continually adds support for new runtimes.</p>

<table cellspacing="0" cellpadding="0" border="0" class="full margin-bottom-large">
    <thead>
        <tr>
            <th style="width: 50px"></th>
            <th style="width: 120px">Name</th>
            <th>Image</th>
            <th>Architectures</th>
            <th>Platforms</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($runtimes as $key => $runtime): ?>
        <tr>
            <td><img src="" data-ls-attrs="src=/images/runtimes/<?php echo $this->escape($runtime['logo'] ?? ''); ?>" alt="Function Env." class="avatar xxs" /></td>
            <td><span data-general-copy><?php echo $this->escape($key); ?> </span></td>
            <td><a href="https://hub.docker.com/r/<?php echo $this->escape(strtok($runtime['image'], ':')); ?>" target="_blank" rel="noopener"><?php echo $this->escape($runtime['image'] ?? ''); ?> <i class="icon-link-ext"></i></a></td>
            <td><?php echo $this->escape(implode(' / ', $runtime['supports'] ?? [])); ?></td>
            <td>
                <?php if (isset($runtimes[$key]["cloud"])): ?>
                    <span class="tag green">Cloud</span>
                <?php endif; ?>
                <span class="tag">Self-hosted</span>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

[TODO: @matej Label which ones are cloud only, idk how to do cleanly]
