<p>
    Making the move to Appwrite Cloud? We've got your back.
    Migrations makes it easy as easy as a couple clicks to move all of your self hosted data to Appwrite Cloud.
</p>

<h2><a href="#notices" id="notices">Things to keep in mind</a></h2>

<ol class="margin-top margin-bottom-large text-size-normal">
    <li>Data transferred by migrations will reset `$createdAt` and `$updatedAt` timestamps to the date of the migration.</li>
</ol>

<h2><a href="#migration-process" id="migration-process">Migrating to Cloud from Self Hosted</a></h2>
<p>
    To begin migrating to Appwrite Self Hosted make sure to read the <a href="/docs/migration">migration overview</a>
    and <a href="#notices">things to keep in mind</a> sections above.
</p>

<p>
    Navigate to your Self Hosted instance and click on the <b>Migrations</b> tab.

    From there you can click on the <b>Deploy to Cloud</b> button, you will then be redirected to Appwrite Cloud.

    Once your at Appwrite Cloud you will be prompted to select the organization aswell as the option to either create a new project
    or select an existing project to migrate to.

    After you have selected the project you want to migrate to you will be asked what data you want to migrate. You can select
    to migrate users, databases, documents, files and functions. Once you have selected what data you want to migrate you can
    click on the <b>Start Migration</b> button to begin the migration process.
</p>

<div class="notice">
    <h2>Keep in mind</h2>
    <p>Your Self Hosted instance will generate a API Key in the background to pass to Cloud. You can revoke this key after the migration process is complete.</p>
</div>