<p>
    Moving your app from another platform to Appwrite? 
    You can move your app from Firebase, Supabase, NHost, and even other Appwrite projects to another Appwrite project using Migrations.
    Migrations will automatically move accounts, database documents, and storage files from one source to another.
</p>

<h2><a href="#supported-sources" id="supported-sources">Supported sources</a></h2>
<p>
    You can transfer from these sources to an Appwrite project.
</p>

<table cellspacing="0" cellpadding="0" border="0" class="full margin-bottom-large text-size-small vertical">
    <thead>
        <tr>
            <th style="width: 80px"></th>
            <th style="width: 180px">Source</th>
            <th style="width: 120px"></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>
                [IMAGE]
            </td>
            <td>
                Firebase
            </td>
            <td>
                <p><a href="/docs/migration-firebase"><i class="icon-angle-circled-right margin-start-negative-tiny margin-end-tiny"></i> Migrate from Firebase</a></p>
            </td>
        </tr>
        <tr>
            <td>
                [IMAGE]
            </td>
            <td>
                Supabase
            </td>
            <td>
                <p><a href="/docs/migration-supabase"><i class="icon-angle-circled-right margin-start-negative-tiny margin-end-tiny"></i> Migrate from Supabase</a></p>
            </td>
        </tr> 
        <tr>
            <td>
                [IMAGE]
            </td>
            <td>
                NHost
            </td>
            <td>
                <p><a href="/docs/migration-nhost"><i class="icon-angle-circled-right margin-start-negative-tiny margin-end-tiny"></i> Migrate from NHost</a></p>
            </td>
        </tr>         
    </tbody>
</table>

<h2><a href="#limitations" id="limitations">Limitations</a></h2>
<p>
    Migrations cannot transfer all data perfectly, so certain fields, such as <code>$createdAt</code> and <code>$updatedAt</code>, may not be transferred. 
    More information can be found on the migration page for each source.
</p>