<p>
  Moving your project from Supabase to Appwrite?
  Appwrite Migrations can help you streamline the process.
  
  Here's what you need to know to get started.
</p>

<h2><a href="#notices" id="notices">Things to keep in mind</a></h2>

<ol class="margin-top margin-bottom-large text-size-normal">
  <li>Appwrite will not incur usage charges during migrations, but Supabase may still incur service charges.</li>
  <li>Appwrite's Databases services supports a different set of features as PostgreSQL. Some features like advanced indexes, Postgres functions and scheduling will not be migrated.</li>
  <li>OAuth users will not be transferred. Users will need to re-authenticate with your OAuth provider after the migration is complete.</li>
</ol>

<h2><a href="#migration-process" id="migration-process">Migrating to Appwrite from Supabase</a></h2>
<p>
  To begin migrating to Appwrite make sure to read the <a href="/docs/migrations">migration overview</a> 
  and <a href="#notices">things to keep in mind</a> sections above.
</p>
   
<ol class="margin-top margin-bottom-large text-size-normal">
  <li>
    Create a new project and click on the <b>Migrations</b> tab.
  </li>
  <li>
    Click on the <b>Create Migration</b> button and select <b>Supabase</b> as your source.
  </li>
  <li>
    Enter the credentials following the <a href="#credentials">instructions below</a> and click <b>Next</b>.
  </li>
  <li>
    Select the resources you want to migrate and finally click <b>Start migration</b> to begin the migration process.
  </li>
</ol>

<h3><a href="#credentials" id="credentials">Credentials</a></h3>

<p>Enter all the following credentials from your Supabase project.</p>

<ol class="margin-top margin-bottom-large text-size-normal">

  <li>
      <b>Region</b> - The region your Supabase project is hosted in. This can be found in your Supabase project environment variables as <b>Supabase_REGION</b>.
  </li>
  <li>
      <b>Host</b> - The host of your Supabase Database, this can be found in your Supabase project settings under <b>Database Settings</b> and <b>Host</b>.
  </li>
  <li>
      <b>Port</b> - The port of your Supabase Database, this can be found in your Supabase project settings under <b>Database Settings</b> and <b>Port</b>. By default this is <b>5432</b>.
  </li>
  <li>
      <b>Username</b> - The username of your Supabase Database, this can be found in your Supabase project settings under <b>Database Settings</b> and <b>Username</b>.
  </li>
  <li>
      <b>Password</b> - The password of your Supabase Database, this was set when you created your Supabase project. If you forgot your password, you can reset it within <b>Database Settings</b>.
  </li>
  <li>
      <b>Endpoint</b> - This is the endpoint of your Supabase instance under <b>Project Settings > API</b>. This is used to migrate your files.
  </li>
  <li>
      <b>API Key</b> - This is the key of your Supabase instance under <b>Project Settings > API</b>. This is used to migrate your files. Make sure to use the hidden <b>service_role</b> key.
  </li>
</ol>
