<p>Product lifecycle stages define how we stage, release, and retire product functionality. By sharing these stages, we hope to help you plan your use of our products and features.</p>

<div class="notices note">
    <p><a href="/policy/terms">Our terms of service</a> govern your use of Appwrite and cover details of eligibility, content, use, payments &amp; billing, and warranties. This document is not a contract and all use of Appwrite’s services are subject to the <a href="/policy/terms">terms of service</a>.</p>
</div>

<h2>Overview</h2>

<table class="full vertical text-size-small">
    <thead>
        <tr>
            <th>Stage</th>
            <th>Availability</th>
            <th>Support</th>
            <th>Production</th>
            <th>Charges</th>
            <th>Retirement</th>
        </tr>
    </thead>

    <tbody>
        <tr>
            <td data-title="Stage: ">Beta</td>
            <td data-title="Availability: ">By invitation</td>
            <td data-title="Support: ">No formal support</td>
            <td data-title="Production: ">No</td>
            <td data-title="Charges: ">None</td>
            <td data-title="Retirement: ">Can be discontinued without notice</td>
        </tr>

        <tr>
            <td data-title="Stage: ">Limited Availability</td>
            <td data-title="Availability: ">Select customers</td>
            <td data-title="Support: ">Full</td>
            <td data-title="Production: ">Partially</td>
            <td data-title="Charges: ">Per standard terms (except SLAs)</td>
            <td data-title="Retirement: ">Follows the <a href="#retirement">retirement process</a></td>
        </tr>

        <tr>
            <td data-title="Stage: ">General Availability</td>
            <td data-title="Availability: ">All customers</td>
            <td data-title="Support: ">Full</td>
            <td data-title="Production: ">Yes</td>
            <td data-title="Charges: ">Per standard terms (except SLAs)</td>
            <td data-title="Retirement: ">Follows the <a href="#retirement">retirement process</a></td>
        </tr>
    </tbody>
</table>

<h2>Lifecycle Stages</h2>

<h3>Beta</h3>

<p>Beta offerings are initial releases of potential future products or features. Customers who participate in our beta programs have the opportunity to test, validate, and provide feedback on future functionality, which helps us focus our efforts on what provides the most value to our customers.</p>

<ul>
    <li><p><b>Customer availability</b>: Participation in beta releases is by invitation, and customers may choose not to participate. Beta invitations may be public or private.</p></li>

    <li><p><b>Support</b>: Beta releases are unsupported.</p></li>

    <li><p><b>Production readiness</b>: Beta releases may not be appropriate for production-level workloads.</p></li>

    <li><p><b>Charges</b>: There is no charge for beta functionality. However, free use of beta offerings may be discontinued at any point in time.</p></li>

    <li><p><b>Retirement</b>: At the end of a beta release, Appwrite will determine whether to continue an offering through its lifecycle. We reserve the right to change the scope of or discontinue a Beta product or feature at any point in time without notice, as outlined in our terms of service.</p></li>
</ul>

<h3>Limited Availability</h3>

<p>Limited Availability offerings are fully functional products and features that are enabled for specific user groups as part of an incremental roll-out strategy.</p>

<ul>
    <li><p><b>Customer availability</b>: Limited Availability functionality is rolled out to specific segments of users in addition to or in place of existing functionality.</p></li>

    <li><p><b>Support</b>: Limited Availability offerings are provided with the same level of support as General Availability features and products.</p></li>

    <li><p><b>Production readiness</b>: They are expected, but not guaranteed, to perform for production-level workloads. Where appropriate, SLAs are defined and measured, though not backed by a process of issuing credits.</p></li>

    <li><p><b>Charges</b>: Limited Availability offerings follow our standard pricing and billing procedures and are charged (or not) in the same way that General Availability offerings are, except for SLA refunds.</p></li>

    <li><p><b>Retirement</b>: In the event, we retire a Limited Availability product before General Availability, we will strive to follow the Retirement procedures outlined below.</p></li>
</ul>

<h3>General Availability</h3>

<p>General Availability offerings are fully functional products that are openly accessible to all Appwrite customers for production use.</p>

<ul>
    <li><p><b>Customer availability</b>: All Appwrite users have access to General Availability offerings.</p></li>

    <li><p><b>Support</b>: All General Availability offerings are fully supported.</p></li>

    <li><p><b>Production readiness</b>: General Availability offerings can be used for production-level workloads.</p></li>

    <li><p><strong>Charges</strong>: General Availability offerings follow our standard pricing and billing procedures.</p></li>

    <li><p><strong>Retirement</strong>: General Availability offerings follow the Retirement procedures outlined below.</p></li>
</ul>

<h2>Retirement</h2>

<p>The decision to retire or deprecate features follows a rigorous process including understanding the demand, use, impact of feature retirement and, most importantly, customer feedback. Our goal is to invest resources in areas that will add the most value for most customers</p>

<p>Appwrite is committed to being clear, transparent, and proactive when interacting with our customers, especially about changes to our platform. To that end, we will make best efforts to follow these guidelines when retiring functionality:</p>

<ul>
    <li><p><b>Advance notice</b>. For minor changes resulting in retirement or deprecation of functionality, we will attempt to proactively notify customers at least 3 months in advance. For retirement of major features or products, we will attempt to notify customers at least 6 months in advance.</p></li>

    <li><p><b>Viable alternatives</b>. Appwrite will strive to provide viable alternatives to our customers when retiring functionality. These may be alternative offerings from Appwrite or recommended alternatives from 3rd party providers. Where possible and appropriate, Appwrite will automatically migrate customers to alternatives for retired functionality.</p></li>

    <li><p><b>Continued support</b>. Appwrite commits to providing continued support for functionality until its retirement date.</p></li>
</ul>

<p>We may need to accelerate the timeline for the retirement of functionality in extenuating circumstances, such as essential changes necessary to protect the integrity of our platform or the security of our customers and others. In these cases, it is important that those changes occur as quickly as possible.</p>

<p>Similarly, integrated third party software or services may need to be retired due to the third-party decision to change or retire their solution. In these situations, the pace of retirement will be out of our control.</p>